


import Footer from "./components/Footer/Footer";
import MainNavigation from "./components/Main-navigation/Main-navigation";

export const metadata = {
  title: "The info-app",
  description: "Generated by Plamen Kostov",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MainNavigation />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
